name: sign_language_app
description: A Flutter app for sign language translation to Spanish text.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP y networking
  http: ^1.1.0
  
  # State management
  provider: ^6.0.0
  
  # Local storage
  shared_preferences: ^2.2.0
  
  # Video
  video_player: ^2.7.0
  camera: ^0.10.0
  
  # Media
  image_picker: ^1.0.0
  
  # Date/time
  intl: ^0.18.0
  
  # UI
  flutter_launcher_icons: ^0.13.0
  cupertino_icons: ^1.0.2
  google_fonts: ^5.0.0
  
  # Logging
  logger: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

assets:
  - assets/images/
  - assets/icons/

fonts:
  - family: Roboto
    fonts:
      - asset: assets/fonts/Roboto-Regular.ttf
      - asset: assets/fonts/Roboto-Bold.ttf
        weight: 700
